### ISSUE TITLE
Problems installing package - vignettes not compiling

### ISSUE THREAD

**Issue by beeeel** [mlysy/subdiff#8]
Hi, I'm a newbie to R so it's possible I've missed a basic step. I installed R 3.4.4 via apt on Ubuntu 18.04, then followed the steps in subdiff/README.md. I also had to install [SuperGauss](https://github.com/mlysy/supergauss) using devtools::install_github, and a couple of other dependencies including the FFTW library.

Initially, testthat::test_package complained that there were no tests installed. I manually cloned the git repo for subdiff into ~/R/x86_64-pc-linux-gnu-library/3.4/subdiff, and now it passes all tests first try. I've been able to compile the .Rd files into a pdf, but I cannot use the vignettes: `vignette("subdiff")` returns warning `vignette ‘subdiff’ not found`. Apparently they are supposed to be compiled when the package is installed, but the vignette source files are absent from the install directory prior to cloning the github repo manually.

Please can you help me work out why my install hasn't happened properly, and fix it?

**Comment by mlysy** [comment]
Hi @beeeel, apologies for the slow response...

How about:
```r
devtools::install_github("mlysy/subdiff", 
                         build_vignettes = TRUE, INSTALL_opts = "--install-tests")
```

**Comment by beeeel** [comment]
Hi, thanks for your answer! The argument "INSTALL_opts" wasn't recognised so I tried using "build_opts" instead and that doesn't understand --install-tests. I also had to install pandoc as a dependency.

In any case, I get an error about the vignette for msd_conventions.Rmd:

```
> devtools::install_github("mlysy/subdiff", build_vignettes = TRUE, build_opts = "--install-tests", force = TRUE)
Downloading GitHub repo mlysy/subdiff@HEAD
   Warning: unknown option ‘--install-tests’
✔  checking for file ‘/tmp/RtmpfJhegz/remotes74e27da0af16/mlysy-subdiff-21511d3/DESCRIPTION’ ...
─  preparing ‘subdiff’:
✔  checking DESCRIPTION meta-information ...
─  cleaning src
─  installing the package to build vignettes
E  creating vignettes (16.1s)
   Quitting from lines 59-93 (msd_conventions.Rmd) 
   Error: processing vignette 'msd_conventions.Rmd' failed with diagnostics:
   could not find function "%>%"
   Execution halted
Error: Failed to install 'subdiff' from GitHub:
  System command 'R' failed, exit status: 1, stdout + stderr (last 10 lines):
E> * checking for file ‘/tmp/RtmpfJhegz/remotes74e27da0af16/mlysy-subdiff-21511d3/DESCRIPTION’ ... OK
E> * preparing ‘subdiff’:
E> * checking DESCRIPTION meta-information ... OK
E> * cleaning src
E> * installing the package to build vignettes
E> * creating vignettes ... ERROR
E> Quitting from lines 59-93 (msd_conventions.Rmd) 
E> Error: processing vignette 'msd_conventions.Rmd' failed with diagnostics:
E> could not find function "%>%"
E> Execution halted
```

**Comment by mlysy** [comment]
I've added the [`check-release`](https://github.com/r-lib/actions/tree/v2/examples#quickstart-ci-workflow) GitHub action to confirm that installation works on various platforms and am therefore closing this issue.
